// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9uedvKzn8vaAgAPGTSFWxTUt2nm9DZY4',
    appId: '1:990108223386:web:986fc678e675d624c31c23',
    messagingSenderId: '990108223386',
    projectId: 'cloud-notes-2026',
    authDomain: 'cloud-notes-2026.firebaseapp.com',
    storageBucket: 'cloud-notes-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxE_92IjMWklhsZo7vKAFQAGyT2XryCnY',
    appId: '1:990108223386:android:520d825a7e6d9ba3c31c23',
    messagingSenderId: '990108223386',
    projectId: 'cloud-notes-2026',
    storageBucket: 'cloud-notes-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv6lxuFze42DH9dVGXx_TJnjfQ_oAjh6s',
    appId: '1:990108223386:ios:3d281464f1f9928bc31c23',
    messagingSenderId: '990108223386',
    projectId: 'cloud-notes-2026',
    storageBucket: 'cloud-notes-2026.firebasestorage.app',
    iosBundleId: 'com.example.cloudNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv6lxuFze42DH9dVGXx_TJnjfQ_oAjh6s',
    appId: '1:990108223386:ios:3d281464f1f9928bc31c23',
    messagingSenderId: '990108223386',
    projectId: 'cloud-notes-2026',
    storageBucket: 'cloud-notes-2026.firebasestorage.app',
    iosBundleId: 'com.example.cloudNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9uedvKzn8vaAgAPGTSFWxTUt2nm9DZY4',
    appId: '1:990108223386:web:499366523f8188c4c31c23',
    messagingSenderId: '990108223386',
    projectId: 'cloud-notes-2026',
    authDomain: 'cloud-notes-2026.firebaseapp.com',
    storageBucket: 'cloud-notes-2026.firebasestorage.app',
  );
}
